[files]
extend-exclude = ["Cargo.lock", "target/", "extras/"]

[default]
locale = "en-us"
extend-ignore-identifiers-re = ["[Rr]atatui", "CPY[0-9]+"]

[default.extend-words]
arange = "arange"
extentions = "extentions"
flate = "flate"
fpr = "fpr"
LOD = "LOD"
mis = "mis"
OT = "OT"
Plasticos = "Plasticos"
valu = "valu"
wrk = "wrk"
